version: '3.7'

volumes:
  jenkins-data: {}

services: 

  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
      - ./casc_configs:/var/jenkins_home/casc_configs
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs